'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'Этот класс создан автоматически классом StronglyTypedResourceBuilder
'с помощью такого средства, как ResGen или Visual Studio.
'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
'с параметром /str или перестройте свой проект VS.
'''<summary>
'''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class ProjectResources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Registration.ProjectResources", GetType(ProjectResources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
    '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property GRAPH04() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("GRAPH04", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Поиск локализованного ресурса типа System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property SINEWAVE() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("SINEWAVE", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Помощник построения сечений.
    '''</summary>
    Friend Shared ReadOnly Property str10() As String
        Get
            Return ResourceManager.GetString("str10", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Помощь.
    '''</summary>
    Friend Shared ReadOnly Property str100() As String
        Get
            Return ResourceManager.GetString("str100", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Введение.
    '''</summary>
    Friend Shared ReadOnly Property str1000() As String
        Get
            Return ResourceManager.GetString("str1000", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Создать.
    '''</summary>
    Friend Shared ReadOnly Property str10000() As String
        Get
            Return ResourceManager.GetString("str10000", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Был создан..
    '''</summary>
    Friend Shared ReadOnly Property str10001() As String
        Get
            Return ResourceManager.GetString("str10001", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Не показывать этот диалог в будущем..
    '''</summary>
    Friend Shared ReadOnly Property str10002() As String
        Get
            Return ResourceManager.GetString("str10002", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на OK.
    '''</summary>
    Friend Shared ReadOnly Property str10003() As String
        Get
            Return ResourceManager.GetString("str10003", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на  Мастер поможет Вам правильно построить сечения. Пройдите все этапы по шагам..
    '''</summary>
    Friend Shared ReadOnly Property str1001() As String
        Get
            Return ResourceManager.GetString("str1001", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на &amp;Пропустить этот экран в будущем..
    '''</summary>
    Friend Shared ReadOnly Property str1002() As String
        Get
            Return ResourceManager.GetString("str1002", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Прервать.
    '''</summary>
    Friend Shared ReadOnly Property str101() As String
        Get
            Return ResourceManager.GetString("str101", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на &lt; &amp;Назад.
    '''</summary>
    Friend Shared ReadOnly Property str102() As String
        Get
            Return ResourceManager.GetString("str102", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на &amp;Вперед&gt;.
    '''</summary>
    Friend Shared ReadOnly Property str103() As String
        Get
            Return ResourceManager.GetString("str103", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на &amp;Финиш.
    '''</summary>
    Friend Shared ReadOnly Property str104() As String
        Get
            Return ResourceManager.GetString("str104", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Помощник построения сечений....
    '''</summary>
    Friend Shared ReadOnly Property str15() As String
        Get
            Return ResourceManager.GetString("str15", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Шаг 1.
    '''</summary>
    Friend Shared ReadOnly Property str2000() As String
        Get
            Return ResourceManager.GetString("str2000", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на (Нет).
    '''</summary>
    Friend Shared ReadOnly Property str20000() As String
        Get
            Return ResourceManager.GetString("str20000", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Установите &lt;Курсор Начала&gt; в место, которое будет являться базой начала построения сечений и нажмите кнопку &lt;Построить фиксированные сечения&gt;..
    '''</summary>
    Friend Shared ReadOnly Property str2001() As String
        Get
            Return ResourceManager.GetString("str2001", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Шаг 2.
    '''</summary>
    Friend Shared ReadOnly Property str2002() As String
        Get
            Return ResourceManager.GetString("str2002", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Если необходимо построить дополнительные сечения, то установите &lt;Курсор Начала&gt; в нужное место и нажмите кнопку &lt;Промежуточное&gt;. Если необходимо повторите операцию..
    '''</summary>
    Friend Shared ReadOnly Property str2003() As String
        Get
            Return ResourceManager.GetString("str2003", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Шаг 3.
    '''</summary>
    Friend Shared ReadOnly Property str2004() As String
        Get
            Return ResourceManager.GetString("str2004", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Для вывода таблицы нажмите кнопку &lt;Таблица&gt;..
    '''</summary>
    Friend Shared ReadOnly Property str2005() As String
        Get
            Return ResourceManager.GetString("str2005", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Шаг 4.
    '''</summary>
    Friend Shared ReadOnly Property str2006() As String
        Get
            Return ResourceManager.GetString("str2006", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Команды для этого шага..
    '''</summary>
    Friend Shared ReadOnly Property str2007() As String
        Get
            Return ResourceManager.GetString("str2007", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Финиш!.
    '''</summary>
    Friend Shared ReadOnly Property str3000() As String
        Get
            Return ResourceManager.GetString("str3000", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Неполные Данные..
    '''</summary>
    Friend Shared ReadOnly Property str30000() As String
        Get
            Return ResourceManager.GetString("str30000", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Вы должны ... прежде, чем Вы можете продолжать..
    '''</summary>
    Friend Shared ReadOnly Property str30001() As String
        Get
            Return ResourceManager.GetString("str30001", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Таблица сечений будет записана..
    '''</summary>
    Friend Shared ReadOnly Property str3001() As String
        Get
            Return ResourceManager.GetString("str3001", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Нажмите Финиш!.
    '''</summary>
    Friend Shared ReadOnly Property str3002() As String
        Get
            Return ResourceManager.GetString("str3002", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Ищет локализованную строку, похожую на Сохраните текущие параметры настройки как значение по умолчанию.
    '''</summary>
    Friend Shared ReadOnly Property str3003() As String
        Get
            Return ResourceManager.GetString("str3003", resourceCulture)
        End Get
    End Property
End Class
